# Generated by Django 3.0.5 on 2020-07-04 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smpool_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=500)),
                ('class_subtitle', models.CharField(max_length=500)),
                ('class_text', models.CharField(max_length=500)),
                ('class_type', models.CharField(max_length=500)),
                ('batch_no', models.IntegerField()),
                ('class_start_date', models.CharField(max_length=500)),
                ('class_day', models.CharField(max_length=500)),
                ('class_time', models.CharField(max_length=500)),
                ('class_ph', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='content_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_desc', models.CharField(max_length=500)),
                ('service_cost', models.FloatField()),
                ('manage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course_exam_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=500)),
                ('exam_fees', models.CharField(max_length=500)),
                ('exam_text', models.CharField(max_length=500)),
                ('exam_type', models.CharField(max_length=500)),
                ('exam_ph', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_title', models.CharField(max_length=500)),
                ('module_name', models.CharField(max_length=500)),
                ('course_duration', models.CharField(max_length=500)),
                ('course_fees', models.CharField(max_length=500)),
                ('exam_code', models.CharField(max_length=500)),
                ('exam_fees', models.CharField(max_length=500)),
                ('course_comments', models.CharField(max_length=500)),
                ('course_ph', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='menu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=5000)),
                ('submenu_name', models.CharField(max_length=5000)),
                ('menu_srl', models.CharField(max_length=500)),
                ('menu_desc', models.CharField(max_length=500)),
                ('menu_ph', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='website_content_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_title', models.CharField(max_length=500)),
                ('body_subtitle', models.CharField(max_length=500)),
                ('body_text', models.CharField(max_length=5000)),
                ('body_type', models.CharField(max_length=500)),
                ('body_pos', models.CharField(max_length=500)),
                ('body_page', models.CharField(max_length=500)),
                ('body_pic_path', models.CharField(max_length=500)),
                ('menuid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smpool_app.menu_info')),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
        migrations.AddField(
            model_name='course_info',
            name='bodyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smpool_app.website_content_info'),
        ),
        migrations.AddField(
            model_name='course_exam_info',
            name='bodyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smpool_app.website_content_info'),
        ),
        migrations.AddField(
            model_name='class_info',
            name='bodyid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smpool_app.website_content_info'),
        ),
    ]
