# Generated by Django 3.0.5 on 2020-07-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpool_app', '0002_auto_20200703_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_content_info',
            name='body_area',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
