# Generated by Django 3.0.5 on 2020-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpool_app', '0003_website_content_info_body_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_info',
            name='class_code',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_exam_info',
            name='exam_code',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_info',
            name='course_code',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_info',
            name='menu_code',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website_content_info',
            name='body_code',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
